### ISSUE TITLE
Character Sheets Do Not Load

### ISSUE THREAD

**Issue by heyyitskelvi** [foundryvtt/dnd5e#2050]
Character sheets do not open following 2.1.2

```
foundry.js:747 Error: An error occurred while rendering ActorSheet5eCharacter 58. ENOENT: no such file or directory, open 'C:\Users\USERNAME\AppData\Local\FoundryVTT\Data\systems\dnd5e\templates\actors\character-sheet.hbs'
    at i.<anonymous> (foundry.js:6883:41)
    at i.value (socket.js:309:17)
    at i.value (socket.js:239:22)
    at x.emit (index.mjs:136:20)
    at s.value (manager.js:200:14)
    at x.emit (index.mjs:136:20)
    at a.value (index.js:119:51)
    at s.value (manager.js:192:22)
    at x.emit (index.mjs:136:20)
    at a.value (socket.js:323:26)
onError @ foundry.js:747
(anonymous) @ foundry.js:5069
Promise.catch (async)
render @ foundry.js:5067
render @ foundry.js:6394
_onClickLeft2 @ foundry.js:47378
callback @ foundry.js:27813
_handleClickLeft2 @ foundry.js:28027
_handleMouseDown @ foundry.js:27989
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processPointerDown @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.findHit @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerDown @ interaction.min.mjs:8
```

**Comment by heyyitskelvi** [comment]
A manual reinstall of the system fixed the issue.
