### ISSUE TITLE
Unable to open token configuration

### ISSUE THREAD

**Issue by ravingdragoon** [foundryvtt/dnd5e#2300]
I am not able to open the token or prototype token configuration for any pc or npc since updating to DnD5e 2.2.0

This occurs with all modules disabled.

I get the following error:
```
TypeError: An error occurred while rendering TokenConfig 53. Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at TokenDocument5e._getTrackedAttributesFromSchema (token.mjs:55:82)
    at TokenDocument5e.getTrackedAttributes (token.mjs:24:67)
    at TokenConfig.getData (foundry.js:70956:53)
    at async TokenConfig._render (foundry.js:5108:18)
    at async TokenConfig._render (foundry.js:5822:5)
onError @ foundry.js:747
```

**Comment by MaxPat931** [comment]
Duplicate of recently resolved issue https://github.com/foundryvtt/dnd5e/issues/2295
