### ISSUE TITLE
Token or Prototype Token unclickable

### ISSUE THREAD

**Issue by bradleyquinn** [foundryvtt/dnd5e#2307]
TypeError: An error occurred while rendering TokenConfig 75. Cannot convert undefined or null to object
[Detected 1 package: system:dnd5e]
    at Function.keys (<anonymous>)
    at TokenDocument5e._getTrackedAttributesFromSchema (token.mjs:55:82)
    at TokenDocument5e.getTrackedAttributes (token.mjs:24:67)
    at TokenConfig.getData (foundry.js:70956:53)
    at async TokenConfig._render (foundry.js:5108:18)
    at async TokenConfig._render (foundry.js:5822:5)

onError | @ | foundry.js:747
-- | -- | --
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁Hooks.onError#lib-wrapper | @ | listeners.js:138
  | 🎁Hooks.onError#0 | @ | libWrapper-wrapper.js:187
  | (anonymous) | @ | foundry.js:5069
  | Promise.catch (async) |   |  
  | render | @ | foundry.js:5067
  | render | @ | foundry.js:6394
  | render | @ | foundry.js:70940
  | _onConfigureToken | @ | foundry.js:61422
  | onclick | @ | foundry.js:61380
  | (anonymous) | @ | foundry.js:5239
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2

**Comment by MaxPat931** [comment]
Duplicate of recently resolved issue https://github.com/foundryvtt/dnd5e/issues/2295
