### ISSUE TITLE
v11 DnD5e v2.2.1: Error when deleting advancements still persists.

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#2316]
I updated as soon as the patch came out to 2.2.1 and tried to delete an advancement I made on a custom fighter class rework and it throws this into the console:

foundry.js:67285 Cannot assign to read only property '_id' of object '#<ScaleValueAdvancement>'

TypeError: Cannot assign to read only property '_id' of object '#<ScaleValueAdvancement>'
    at SchemaField._cleanType (commons.js:5302:20)
    at SchemaField.clean (commons.js:4983:19)
    at ScaleValueAdvancement.cleanData (commons.js:6915:26)
    at AdvancementField._cleanType (fields.mjs:23:27)
    at AdvancementField.clean (commons.js:4983:19)
    at commons.js:5764:42
    at Array.map (<anonymous>)
    at ArrayField._cleanType (commons.js:5764:20)
    at ArrayField.clean (commons.js:4983:19)
    at SchemaField._cleanType (commons.js:5302:28)

Reproduction: Try to modify a class made in 2.1 while in 2.2.1 (originally a problem in 2.2.0)

**Comment by Zanderaf** [comment]
Image of the error
![image](https://github.com/foundryvtt/dnd5e/assets/65571170/4b74f263-6275-4f5c-942b-11864a4b3924)
