### ISSUE TITLE
Attribute rolls are no longer working after the upgrade to 2.2.1

### ISSUE THREAD

**Issue by geoidesic** [foundryvtt/dnd5e#2326]
```
se-sheet.mjs:1355 Uncaught TypeError: undefined. Cannot read properties of null (reading 'dataset')
[Detected 1 package: system:dnd5e]
    at Tidy5eSheet._onRollSkillCheck (base-sheet.mjs:1355:60)
    at HTMLHeadingElement.dispatch (jquery.min.js:2:43064)
    at y.handle (
    
```

**Comment by MaxPat931** [comment]
Looks like an issue with TidySheet

**Comment by geoidesic** [comment]
Ok thx, I see there is a PR for it https://github.com/sdenec/tidy5e-sheet/pulls
