### ISSUE TITLE
Error when configuring the prototype token for a group actor on v11

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#2328]
Create a new group actor and configure the prototype token. When you do this in Foundry v11 (tested with 11.299) then you get an error:

```
TypeError: An error occurred while rendering TokenConfig 43. Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at TokenDocument5e._getConfiguredTrackedAttributes (foundry.js:24923:12)
    at TokenDocument5e.getTrackedAttributes (foundry.js:24809:27)
    at TokenDocument5e.getTrackedAttributes (token.mjs:23:43)
    at TokenConfig.getData (foundry.js:80304:53)
    at async TokenConfig._render (foundry.js:5726:18)
    at async TokenConfig._render (foundry.js:6444:5)
```

I checked the code in `_getConfiguredTrackedAttributes` and I think I see the bug. It get's info based on the actor type but it looks like the it's missing for group actors.

```js
if ( type ) config = foundry.utils.deepClone(CONFIG.Actor.trackableAttributes[type]);
```

I checked `CONFIG.Actor.trackableAttributes` and I don't see an entry for `group` actors. I think we need to fill that in.

**Comment by aaclayton** [comment]
Fixed for next patch.
