### ISSUE TITLE
The Combat Tracker RollAll fails if one or more combatants have no actor assigned

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/dnd5e#2335]
### What happened?

The Combat Tracker RollAll fails if one or more combatants have no actor assigned.

The issue seems to be that while there is a check for actor in `Combatant#getInitiativeRoll`, because the `Combat#rollInitiative` defaults the formula to null, it gets passed to `Combatant#getInitiativeRoll` which does not use the default d20.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Create combat with at leas one combatant missing the actor
- Hit the roll all button
- Check console error

### What core version are you reporting this for?

V11 - 300

### Relevant log output

```shell
Uncaught (in promise) Error: undefined. Roll.safeEval produced a non-numeric result from expression ""
[No packages detected]
    at D20Roll.safeEval (foundry.js:10372:13)
    at D20Roll._evaluateTotal (foundry.js:10277:36)
    at D20Roll._evaluate (foundry.js:10225:24)
    at D20Roll.evaluate (foundry.js:10185:25)
    at Combat.rollInitiative (foundry.js:20867:18)
    at Combat.rollAll (foundry.js:20916:17)
    at CombatTracker5e._onCombatControl (foundry.js:85133:36)
    at HTMLAnchorElement.<anonymous> (foundry.js:85070:51)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by pgervais70** [comment]
I think it might be related to this bug, but when the roll all button in the combat tracker is clicked. The dnd5e.preRollInitiative hook is never called. 
which is not the case when clicking individually for each combatant.
