### ISSUE TITLE
After updating a token, some values of their items disappear.

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2354]
Specifically saving throw labels and checks.

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/118e27a6-f7d5-4905-9c49-eca3dc4797ef)

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/da83a1a2-9fd7-423a-baa6-b6dd21d180d2)

**Comment by kaelad02** [comment]
What version of Foundry does this happen with? (I saw some context on the Discord, just trying to capture it here)

**Comment by krbz999** [comment]
FVTT 11.302+.

**Comment by phenomen** [comment]
I've also noticed that Weight and Cost of items reset to 0 when you equip an item.

**Comment by SirAron111** [comment]
Jep having the same problem come up on my end after updating.

**Comment by kaelad02** [comment]
I found that the easiest way to reproduce this was just by dropping an unlinked token on a scene. I imported the Acolyte from the Monsters SRD compendium and I checked that the labels on the Sacred Flame spell were accurate. I could see the `save` label was there. Then I dropped an Acolyte token on a scene and did the same check on that token's copy and the `save` label was missing. I added some logging and noticed that `Item5e#prepareDerivedData` was called after `Item5e#prepareFinalAttributes` was called so I generated a stack trace for that final call.

The first line was just a `console.log` message, the second was a stack trace generated by `new Error().stack`

```
Item5e prepareDerivedData where labels is reset Cure Wounds
item.mjs:309 Error
    at Item5e.prepareDerivedData (item.mjs:309:17)
    at Item5e.prepareData (foundry.js:14144:12)
    at Item5e._safePrepareData (foundry.js:14119:14)
    at ActorDelta.prepareEmbeddedDocuments (foundry.js:14165:13)
    at ActorDelta.prepareData (foundry.js:14142:12)
    at ActorDelta.prepareData (foundry.js:18250:11)
    at ActorDelta._safePrepareData (foundry.js:14119:14)
    at ActorDelta._initialize (foundry.js:13947:19)
    at ActorDelta._initialize (foundry.js:18227:11)
    at new DataModel (commons.js:6812:12)
    at new Document (commons.js:7474:3)
    at new BaseActorDelta (commons.js:8964:3)
    at new ClientDocumentMixin (foundry.js:13911:7)
    at new ActorDelta (foundry.js:18214:1)
    at TokenDocument5e.<anonymous> (commons.js:12453:20)
    at get actor [as actor] (foundry.js:24586:51)
    at get actor [as actor] (foundry.js:53935:26)
    at Token5e.drawEffects (foundry.js:54881:31)
    at Token5e._draw (foundry.js:54482:16)
    at async foundry.js:28096:7
```

I'm not sure how to fix the missing labels issue, but hopefully this info helps. I did this on Foundry 11.302 and dnd5e 2.2.1.

**Comment by kaelad02** [comment]
I think I see what's happening. `Actor5e` added an extra phase to how `prepareData` works with that `Item5e#prepareFinalAttributes` function. That's there for certain item properties that depend on the owned actor's derived data. We could fix it by creating an `ActorDelta5e` class to do the same thing with unlinked tokens.
