### ISSUE TITLE
Migration to v2.2.2 triggers validation error on an unlinked token's item name/type

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#2361]
Steps to reproduce:
1. Start with a world on version 2.2.1 or earlier and drag an unlinked token to a scene. I don't know if there needs to be anything special about the actor or the items on it. Mine was an actor with just one item on it, a weapon.
2. Upgrade the dnd5e system to 2.2.2 and start the world
3. When the migration runs it'll show a error notification about a failed migration
4. Open the console to see the details of the error (shown below)

```
Migrating Actor document Spiritual Weapon
Migrating Scene document blank
[5XB4lhMUwznOXfxl] validation errors:
  name: may not be undefined
  type: may not be undefined
Error:  [5XB4lhMUwznOXfxl] validation errors:
  name: may not be undefined
  type: may not be undefined
    at DataModelValidationFailure.asError (/resources/app/common/data/validation-failure.mjs:81:12)
    at Object.validate (/resources/app/common/abstract/data.mjs:308:59)
    at new DataModel (/resources/app/common/abstract/data.mjs:62:10)
    at new Document (/resources/app/common/abstract/document.mjs:17:16)
    at new BaseItem (/resources/app/common/documents/item.mjs:31:1)
    at new ServerDocumentMixin (/resources/app/dist/database/backend/server-document.mjs:1:507)
    at new Item (/resources/app/dist/database/documents/item.mjs:1:251)
    at new <anonymous> (/resources/app/dist/database/backend/embedded-delta.mjs:1:102)
    at Map.createDocument (/resources/app/common/abstract/embedded-collection-delta.mjs:48:12)
    at Map._createOrUpdate (/resources/app/common/abstract/embedded-collection-delta.mjs:107:21)
```

With that scene active, I ran this to find the token/actor with an item with that ID.

```js
canvas.scene.tokens.find(t => t.actor.items.some(i => i.id === "5XB4lhMUwznOXfxl"))
```

It told me it was my Spiritual Weapon token, an NPC I created to use for the spell of the same name. I grabbed the item with that ID in the console and it looked fine to me. It had a `name` and `type` and they were exactly as I expected them to be. I refreshed the browser and I didn't see any errors this time and the actor and item worked as expected.

Tested on Foundry 11.302 and dnd5e 2.2.2. A few people have reported it on the Discord so I know I'm not the only one. If I get any other details from there, I'll add it to this issue.

**Comment by Fyorl** [comment]
I'm not able to reproduce this with the provided steps.

> Tested on Foundry 11.302 and dnd5e 2.2.2.

This is also not the latest version of the core software.

**Comment by txm3278** [comment]
This can be reproduced with the "A House Divided" adventure on foundry v11.305. 

Create the world on dnd5e 2.2.1 then update dnd5e to 2.2.2 and launch the "A House Divided" world.

**Comment by MiniGrief** [comment]
I'm getting the issue too on most of my worlds. These worlds were created in v9 or v10 and migrated forward since then. Any of my worlds created in v11 seem unaffected (however they don't have many scenes with tokens on). Tested with 11.304 and 11.305 migrating from 2.2.1 - 2.2.2. I have tried with safe configuration enabled to ensure it wasn't a module causing it.

It doesn't seem to actually affect anything from a quick look at the scenes the errors originate from, though I'm sure the internal data for these would say otherwise. Also unlinked tokens are not the only problem as scenes (with no tokens placed or anything else done other than walling/lighting) are sometimes giving the same error.

**Comment by alessiocali** [comment]
Likewise, I'm getting this error and my world was created on v10. My foundry version is 11.305

**Comment by alessiocali** [comment]
If it is of any help, the tokens were from a map full with dead NPCs from a session that somehow didn't get removed. Removing all token from that specific scene made the migration continue and succeed.

Oddly again, after reloading the world right after the conversion, the tokens were back.

**Comment by Fyorl** [comment]
I was eventually able to reproduce this (by accident). I've investigated and determined that it is an issue within the core software, rather than the dnd5e system specifically.
