### ISSUE TITLE
V11.305 dnd2.2.2 Toggling ActiveEffect gives a read only TypeError

### ISSUE THREAD

**Issue by OhhLoz** [foundryvtt/dnd5e#2368]
Hi,
I'm trying to update a module to V11 and whilst calling toggleEffect() on a Token using a temporary effect attached to a Feature within a compendium it throws this error:

Uncaught (in promise) TypeError: Cannot assign to read only property '_id' of object '#<ActiveEffect5e>'
    at SchemaField._cleanType (commons.js:5300:20)
    at SchemaField.clean (commons.js:4981:19)
    at ActiveEffect5e.cleanData (commons.js:6949:26)
    at TokenDocument5e.toggleActiveEffect (foundry.js:24892:11)
    at Token5e.toggleEffect (foundry.js:55561:44)
    at Object.addEffect (module.js:297:17)
    at SocketlibSocket._executeLocal (socketlib.js:192:15)
    at SocketlibSocket.executeAsGM (socketlib.js:90:16)
    at handleAction (module.js:132:18)

I checked to ensure the Token and Effect are fetched correctly so I have no idea how to get around this as the same code worked for Foundry v10.

Whilst searching amongst the issues here it seems similar to #2294 at a cursory glance, which was fixed by calling toObject() in the backend of the dnd5e system. However, I don't wish to presume.

**Comment by OhhLoz** [comment]
![image](https://github.com/foundryvtt/dnd5e/assets/22823143/1f34a6e5-91cc-466c-85a5-d99b894ddc9c)
This is the ActiveEffect that is attempting to be used. Is it because it has no "_id" field, only a "id" field
