### ISSUE TITLE
canot open many compendium entrys on german language

### ISSUE THREAD

**Issue by R0TEAM** [foundryvtt/dnd5e#2603]
error:

Uncaught (in promise) TypeError: undefined. m.replace is not a function
[Detected 2 packages: FoundryVTT-dnd5e-DE, babele]
    at FieldMapping.convertSource [as converter] (dnd5e-de.js:546:46)
    at FieldMapping.translate (babele.js:1006:26)
    at FieldMapping.map (babele.js:989:28)
    at babele.js:1072:62
    at Array.reduce (<anonymous>)
    at CompendiumMapping.map (babele.js:1072:28)
    at TranslatedCompendium.translate (babele.js:1235:43)
    at Babele.translate (babele.js:763:19)
    at babele.js:78:54
    at Array.map (<anonymous>)
    at 🎁ClientDatabaseBackend.prototype._getDocuments#babele (babele.js:77:27)
    at async CompendiumCollection.getDocuments (foundry.js:16280:23)
    at async CompendiumCollection.getDocument (foundry.js:16252:23)
    at async Compendium._onClickEntryName (foundry.js:70218:57)

**Comment by Thoeme77** [comment]
Having the same issue. Any plans for a fix of this?

**Comment by Thoeme77** [comment]
Alright, thanks for letting me know and already checking the other issues. I hope you don't mind if the "quick fix" stays here in case someone else needs it. At least until there is an update from the devs.
