### ISSUE TITLE
[BUG] - Cannot open Character Sheet

### ISSUE THREAD

**Issue by Liviu50** [foundryvtt/dnd5e#2606]
After last update no character sheet can be opened.
Npc can still be opened
![image](https://github.com/foundryvtt/dnd5e/assets/96814785/a69df091-b4a9-493c-bec5-c73b06eae3bd)

**Comment by krbz999** [comment]
This is caused by DAE.

(In general, it is best to disable all modules first, to determine it is even a bug with the system.)

**Comment by Liviu50** [comment]
but it was perfectly working before the latest update.
weirdly DAE was not even  mentioned by the console.
Trying to disable and indeed it seems to be working...but why?

**Comment by Liviu50** [comment]
also is DAE any useful? read that 80% of it is already included in the basic foundry...any reason to be kept?

**Comment by unsoluble** [comment]
That's really not a thing we can comment on helpfully here. Suggest hitting up the Foundry discord server for general discussion (and all bug reporting, to start at least) in the future.

**Comment by ZoltanTheDM** [comment]
Not a real solution but I made a temporary fix with changing the offending line (`18322`) in `dnd5e.mjs` to
`type: context.system.details?.type?.label ?? context.system.details.race`

**Comment by stalker168** [comment]
My error when trying to open the player sheet:
```
Error: An error occurred while rendering ActorSheet5eCharacter 143. One of original or other are not Objects!
    at mergeObject (commons.js:2734:13)
    at _mergeUpdate (commons.js:2798:14)
    at mergeObject (commons.js:2755:41)
    at _mergeUpdate (commons.js:2798:14)
    at mergeObject (commons.js:2755:41)
    at _mergeUpdate (commons.js:2798:14)
    at Object.mergeObject (commons.js:2755:41)
    at ActorSheet5eCharacter._render (foundry.js:5748:19)
    at ActorSheet5eCharacter._render (foundry.js:6473:17)
    at ActorSheet5eCharacter.render (foundry.js:5710:10)
    at ActorSheet5eCharacter.render (foundry.js:7052:18)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁ActorSheet.prototype.render#item-piles (libwrapper.js:50:16)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁ActorSheet.prototype.render#0 (libWrapper-wrapper.js:189:20)
    at Token5e._onClickLeft2 (foundry.js:56159:17)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Token.prototype._onClickLeft2#item-piles (libwrapper.js:14:12)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype._onClickLeft2#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:31680:17)
    at #handleClickLeft2 (foundry.js:31885:15)
    at #handleMouseDown (foundry.js:31852:83)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerDown (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerDown (earcut.js:128:75)
```

**Comment by krbz999** [comment]
Suggest hitting up Discord rather than posting module issues on the system repo. @stalker168
