### ISSUE TITLE
Cannot open any actor sheet after upgrading to 2.4.0

### ISSUE THREAD

**Issue by hematic** [foundryvtt/dnd5e#2614]
Initially received this error:

foundry.js:753 TypeError: An error occurred while rendering DNDBeyondCharacterSheet5e 157. Cannot read properties of undefined (reading 'label')
    at DNDBeyondCharacterSheet5e.getData (character-sheet.mjs:42:43)
    at async DNDBeyondCharacterSheet5e.getData (dndbeyond-character-sheet.js:63:23)
    at async DNDBeyondCharacterSheet5e._render (foundry.js:5812:18)
    at async DNDBeyondCharacterSheet5e._render (foundry.js:6532:5)

Disabled that addon but am now getting this similar error with the stock sheet:

foundry.js:753 TypeError: An error occurred while rendering ActorSheet5eCharacter 102. Cannot read properties of undefined (reading 'label')
    at ActorSheet5eCharacter.getData (character-sheet.mjs:42:43)
    at async ActorSheet5eCharacter._render (foundry.js:5812:18)
    at async ActorSheet5eCharacter._render (foundry.js:6532:5)

**Comment by krbz999** [comment]
https://github.com/foundryvtt/dnd5e/issues/2606

**Comment by stalker168** [comment]
My error when trying to open the player sheet:
```
Error: An error occurred while rendering ActorSheet5eCharacter 143. One of original or other are not Objects!
    at mergeObject (commons.js:2734:13)
    at _mergeUpdate (commons.js:2798:14)
    at mergeObject (commons.js:2755:41)
    at _mergeUpdate (commons.js:2798:14)
    at mergeObject (commons.js:2755:41)
    at _mergeUpdate (commons.js:2798:14)
    at Object.mergeObject (commons.js:2755:41)
    at ActorSheet5eCharacter._render (foundry.js:5748:19)
    at ActorSheet5eCharacter._render (foundry.js:6473:17)
    at ActorSheet5eCharacter.render (foundry.js:5710:10)
    at ActorSheet5eCharacter.render (foundry.js:7052:18)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁ActorSheet.prototype.render#item-piles (libwrapper.js:50:16)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁ActorSheet.prototype.render#0 (libWrapper-wrapper.js:189:20)
    at Token5e._onClickLeft2 (foundry.js:56159:17)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Token.prototype._onClickLeft2#item-piles (libwrapper.js:14:12)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype._onClickLeft2#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:31680:17)
    at #handleClickLeft2 (foundry.js:31885:15)
    at #handleMouseDown (foundry.js:31852:83)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerDown (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerDown (earcut.js:128:75)
```
