### ISSUE TITLE
[3.0.0] Error trying to add class or race

### ISSUE THREAD

**Issue by mrcomac** [foundryvtt/dnd5e#2821]
Foundry: 315
DnD5e: 3.0.0
Modules active: 0
(It's a new installation)

Edit:
```
Chrome
Version 120.0.6099.227 (Official Build) (64-bit)

Firefox
115.6.0esr
```

When I create an actor and try to drag and drop class or race to the actor sheet, I can go through the steps however when I click on complete i'm getting the error below:
```
Uncaught DOMException: Element.querySelectorAll: '.items-section:has(.item-list .item:not([hidden]))' is not a valid selector
    _applyFilters item-list-controls.mjs:264
    _applyGrouping item-list-controls.mjs:286
    connectedCallback item-list-controls.mjs:22
    jQuery 6
    _replaceHTML foundry.js:5991
    _render foundry.js:5822
    _render foundry.js:6532
    _render character-sheet-2.mjs:161
    render foundry.js:5769
    render foundry.js:7111
    render foundry.js:14259
    _onUpdate foundry.js:14363
    _onUpdate foundry.js:19131
    _onUpdate document.mjs:98
    _onUpdate actor.mjs:3005
    callback foundry.js:13737
    documents foundry.js:13711
    #handleUpdateDocuments foundry.js:13711
    _updateDocuments foundry.js:13458
    update commons.js:8677
    updateDocuments commons.js:8001
    update commons.js:8098
    _complete advancement-manager.mjs:680
    _forward advancement-manager.mjs:572
    activateListeners advancement-manager.mjs:493
    jQuery 9
    activateListeners advancement-manager.mjs:479
    _render foundry.js:5842
    _render advancement-manager.mjs:464
    render foundry.js:5769
    render advancement-manager.mjs:457
    _forward advancement-manager.mjs:571
    activateListeners advancement-manager.mjs:493
    jQuery 9
    activateListeners advancement-manager.mjs:479
    _render foundry.js:5842
    _render advancement-manager.mjs:464
```

If i keep clicking on continue I get this error:
```
Uncaught (in promise) TypeError: this.step is null
    _forward advancement-manager.mjs:540
    activateListeners advancement-manager.mjs:493
    jQuery 9
    activateListeners advancement-manager.mjs:479
    _render foundry.js:5842
    _render advancement-manager.mjs:464
    render foundry.js:5769
    render advancement-manager.mjs:457
    _forward advancement-manager.mjs:571
    activateListeners advancement-manager.mjs:493
    jQuery 9
    activateListeners advancement-manager.mjs:479
    _render foundry.js:5842
    _render advancement-manager.mjs:464
    render foundry.js:5769
    render advancement-manager.mjs:457
    _forward advancement-manager.mjs:571
    activateListeners advancement-manager.mjs:493
    jQuery 9
    activateListeners advancement-manager.mjs:479
    _render foundry.js:5842
    _render advancement-manager.mjs:464
    render foundry.js:5769
    render advancement-manager.mjs:457
    _forward advancement-manager.mjs:571
    activateListeners advancement-manager.mjs:493
    jQuery 9
    activateListeners advancement-manager.mjs:479
    _render foundry.js:5842
    _render advancement-manager.mjs:464

```

**Comment by mrcomac** [comment]
Chrome
Version 120.0.6099.227 (Official Build) (64-bit)

Firefox
115.6.0esr

**Comment by mrcomac** [comment]
another issue, probably same root cause. When I try to import the compendium to the world

```
foundry.js:68326 Cannot read properties of undefined (reading 'length')
fetch @ foundry.js:68326
advancement-manager.mjs:695 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Preprocessor.advance (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/preprocessor.js:138:35)
    at Tokenizer._consume (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/index.js:270:34)
    at Tokenizer._runParsingLoop (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/index.js:221:29)
    at Tokenizer.write (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/index.js:248:14)
    at parseFragment (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/index.js:42:22)
    at cleanHTML (/home/ubuntu/foundryvtt/resources/app/dist/database/validators.mjs:1:209)
    at HTMLField.sanitizeHTMLField [as sanitize] (/home/ubuntu/foundryvtt/resources/app/dist/database/sanitization.mjs:1:1235)
    at Item._sanitizeFields (/home/ubuntu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7729)
    at Item._sanitizeFields (/home/ubuntu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7956)
    at Item.sanitizeUserInput (/home/ubuntu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7436)
3advancement-manager.mjs:540 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'flow')
    at AdvancementManager._forward (advancement-manager.mjs:540:32)
    at HTMLButtonElement.<anonymous> (advancement-manager.mjs:493:25)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
foundry.js:68326 Cannot read properties of undefined (reading 'length')
fetch @ foundry.js:68326
items-collection.mjs:28 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Preprocessor.advance (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/preprocessor.js:138:35)
    at Tokenizer._consume (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/index.js:270:34)
    at Tokenizer._runParsingLoop (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/index.js:221:29)
    at Tokenizer.write (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/index.js:248:14)
    at parseFragment (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/index.js:42:22)
    at cleanHTML (/home/ubuntu/foundryvtt/resources/app/dist/database/validators.mjs:1:209)
    at HTMLField.sanitizeHTMLField [as sanitize] (/home/ubuntu/foundryvtt/resources/app/dist/database/sanitization.mjs:1:1235)
    at Item._sanitizeFields (/home/ubuntu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7729)
    at Item._sanitizeFields (/home/ubuntu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7956)
    at Item.sanitizeUserInput (/home/ubuntu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7436)
foundry.js:68326 Cannot read properties of undefined (reading 'length')
fetch @ foundry.js:68326
game:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Preprocessor.advance (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/preprocessor.js:138:35)
    at Tokenizer._consume (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/index.js:270:34)
    at Tokenizer._runParsingLoop (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/index.js:221:29)
    at Tokenizer.write (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/tokenizer/index.js:248:14)
    at parseFragment (/home/ubuntu/foundryvtt/resources/app/node_modules/parse5/dist/index.js:42:22)
    at cleanHTML (/home/ubuntu/foundryvtt/resources/app/dist/database/validators.mjs:1:209)
    at HTMLField.sanitizeHTMLField [as sanitize] (/home/ubuntu/foundryvtt/resources/app/dist/database/sanitization.mjs:1:1235)
    at Item._sanitizeFields (/home/ubuntu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7729)
    at Item._sanitizeFields (/home/ubuntu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7956)
    at Item.sanitizeUserInput (/home/ubuntu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7436)
```

**Comment by hardythedrummer** [comment]
I was getting the same error. FWIW, I was able to "fix" it by deleting the world, uninstalling the dnd system, restarting my foundry server, reinstalling dnd5e, and making a new world.

**Comment by arbron** [comment]
@mrcomac The second issue is almost certainly because you need to update the version of Node. V11 requires at least Node 18 and throws errors like that if it is running on an older version.

**Comment by mrcomac** [comment]
Hi @arbron 
node version is v18.19.0

As mentioned by @hardythedrummer, I just restarted the server and it is working now :) .

Thank you guys
