### ISSUE TITLE
Deprecation warning for global `SquareGrid` when opening the Wall Configuration dialog

### ISSUE THREAD

**Issue by Norc** [foundryvtt/dnd5e#3516]
When you double-click any wall to open the Wall Configuration dialog, a deprecation warning is thrown:

```
foundry-esm.js:4565 Error: You are accessing the global "SquareGrid" which is now namespaced under foundry.grid.SquareGrid
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4553:19)
    at get (foundry-esm.js:62832:25)
    at Object.fn (dnd5e.mjs:415:3)
    at #call (foundry.js:608:20)
    at Hooks.callAll (foundry.js:565:17)
    at #draw (foundry.js:24554:11)
    at async Canvas.draw (foundry.js:24482:5)
    at async Scene.view (foundry.js:21009:7)
    at async Game.initializeCanvas (foundry.js:9153:20)
    at async Game.setupGame (foundry.js:8984:5)
logCompatibilityWarning    @    foundry-esm.js:4565
```

Per @dev7355608 , this call is being made by the DND5E game system not core Foundry.

**System information**:
- Foundry V12.320
- DND5E 3.1.2

**Repro steps**:
1. Create a clean new world
2. Draw a normal wall
3. Double-click it

**Comment by arbron** [comment]
Related to the code we use for implementing the various grid measurement modes. Since all of those are available in core as of V12, we should probably just disable all of that code when running that version.
