### ISSUE TITLE
Can't edit weapon, equipment and tools with foundryVTT v12

### ISSUE THREAD

**Issue by Darkriders98** [foundryvtt/dnd5e#3634]
Since I upgraded to the version 12 of FoundryVTT, I can't edit any weapon, equipment or tools and have this error message in the console:

```Error: An error occurred while rendering ItemSheet5e 70. data.toObject is not a function
    at Hooks.onError (foundry.js:630:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5771:13Caused by: TypeError: data.toObject is not a function
    at babele.js:78:75
    at Array.map (<anonymous>)
    at 🎁CONFIG.DatabaseBackend._getDocuments#babele (babele.js:77:27)
    at async CompendiumCollection.getIndex (foundry.js:12947:19)
    at async ItemSheet5e._getItemBaseTypes (item-sheet.mjs:263:24)
    at async ItemSheet5e.getData (item-sheet.mjs:112:18)
    at async ItemSheet5e._render (foundry.js:5814:18)
    at async ItemSheet5e._render (foundry.js:6548:5)
    at async ItemSheet5e._render (foundry.js:7134:5)```

**Comment by arbron** [comment]
You'll have to try this without modules. If you continue to have problems, check out the Discord for troubleshooting first unless you can track down a specific system issue.
