### ISSUE TITLE
Can't play sound twice

### ISSUE THREAD

**Issue by Darkriders98** [foundryvtt/dnd5e#3704]
When I launch the world, I can play sound in a scene with no problems, but if I switch to a new scene, or stop the music to play another one, this only indicates infinite time for the music, like when it is loading, and also got this error:

```Uncaught (in promise) DOMException: Failed to construct 'MediaElementAudioSourceNode': HTMLMediaElement already connected previously to a different MediaElementSourceNode.
    at Sound._createNodes ([MyIP]/scripts/foundry-esm.js:51534:50)
    at #queuePlay ([MyIP]/scripts/foundry-esm.js:51161:12)
    at Sound.play ([MyIP]/scripts/foundry-esm.js:51140:42)
    at Sound.load ([MyIP]/scripts/foundry-esm.js:51073:14)
    at PlaylistSound.sync ([MyIP]/scripts/foundry.js:20069:11)
    at [MyIP]/scripts/foundry.js:20494:83
    at EmbeddedCollection.forEach ([MyIP]/scripts/foundry-esm.js:5026:9)
    at Playlist._onUpdate ([MyIP]/scripts/foundry.js:20494:68)
    at [MyIP]/scripts/foundry-esm.js:55816:15
    at [MyIP]/scripts/foundry-esm.js:55822:43```
   
I also verified if it's not a compatibility issue with some of my module, which is not. But maybe this is a problem from foundry itself since I didn't try with another system.

**Comment by arbron** [comment]
That would definitely be a core issue, because we don't touch anything with sounds.

**Comment by unsoluble** [comment]
Already merged for the next core release.
