### ISSUE TITLE
An invalided uses.max property results in error, not a prepared data warning

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#3716]
On Discord, there was a user that had a Rage ability with some bad data in the `uses.max` property. They were getting this stack trace:

```
activated-effect.mjs:193 Problem preparing the Maximum Uses formula within Rage. TypeError: Cannot read properties of undefined (reading 'name')
    at replaceFormulaData (utils.mjs:105:28)
    at FeatData._prepareFinalFormula (activated-effect.mjs:187:38)
    at FeatData.prepareFinalActivatedEffectData (activated-effect.mjs:129:10)
    at FeatData.prepareFinalData (feat.mjs:72:10)
    at Item5e.prepareFinalAttributes (item.mjs:669:33)
    at actor.mjs:149:37
    at EmbeddedCollection.forEach (foundry-esm.js:5027:9)
    at Actor5e.prepareData (actor.mjs:149:16)
    at Actor5e._safePrepareData (foundry.js:10677:14)
    at Game.initializeDocuments (foundry.js:9067:18)
    at Game.setupGame (foundry.js:8959:10)
    at async Game._initializeGameView (foundry.js:10310:5)
_prepareFinalFormula    @    activated-effect.mjs:193
```

I looked in the code and I think I found the issue. Starting in `activated-effect.mjs` line 187, it calls the `replaceFormulaData` utility function:

```js
replaceFormulaData(value, rollData, { actor: this.parent.actor, property })
```

Then inside that function, in `utils.mjs` on line 105 it references a `this` object but since the function wasn't called with a bound instance, it's causing the stack trace:

```js
const message = game.i18n.format("DND5E.FormulaMissingReferenceWarn", {
  property, name: this.name, references: listFormatter.format(missingReferences)
});
```

I'm guessing this is a simple copy/paste error from where this utility functions originally existed. Oh, and the user on Discord didn't say what version they were using but when I debugged using the 3.2 branch, all the line numbers matched so that's what I'd guess they were using.

**Comment by kaelad02** [comment]
The Discord user confirmed it: D&D 5E 3.2.0 on Foundry Version 12 Build 327
