### ISSUE TITLE
 Automatic Advancement with Subclass Not Working

### ISSUE THREAD

**Issue by Freezor** [foundryvtt/dnd5e#3891]
After updating to the newest Foundry version, I encountered a critical issue affecting basic skill checks and saving throws for my players' characters. The only workaround was to recreate all characters with fresh sheets. However, automatic advancement fails when a character has any subclass, resulting in the following error:

```javascript
module.js:233 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at module.js:233:53
    at Array.map (<anonymous>)
    at Actor5e.prePreUpdateActor (module.js:223:8)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Actor.documentClass.prototype.update#0 (libWrapper-wrapper.js:189:20)
    at AdvancementManager._complete (advancement-manager.mjs:683:18)
    at AdvancementManager._forward (advancement-manager.mjs:575:15)
```

The process fails with a TypeError, indicating that an attempt is made to read the 'value' property of an undefined object.

#### Environment
- **Foundry Version:** 12 Build 330
- **D&D Module Version:** 3.3.1

#### Additional Notes
- This issue did not occur before the latest Foundry update.
- The error might be linked to the interaction between the core system and the D&D module or another installed module.

#### Request for Help
Is this a known issue, or could it be caused by a conflict with another module? Any guidance or troubleshooting tips would be greatly appreciated.

Thanks

**Comment by Freezor** [comment]
I have identified the source of the problem. The issue was caused by the module ["Link Item and Resource DnD5e.](https://github.com/ElfFriend-DnD/foundryvtt-link-item-resource-5e)" It took several hours of trial and error, enabling and disabling various modules, to pinpoint this broken module as the cause.

Is there a way to improve the exception handling to provide more informative error messages? This would greatly reduce the time spent diagnosing such issues in the future.

**Comment by Fyorl** [comment]
> Is there a way to improve the exception handling to provide more informative error messages?

There is no way for us to predict which methods a module might wrap, or what fields it might override. They can affect any part of the system at any level. So this is not feasible, no.
