### ISSUE TITLE
Error upgrading to 3.3.1

### ISSUE THREAD

**Issue by nikkon226** [foundryvtt/dnd5e#3896]
I'm currently on version 3.2.1 and trying to upgrade to 3.3.1, but I get this error:

```
2024-07-26T14:14:14.004411767Z FoundryVTT | 2024-07-26 10:14:14 | [info] Launching World | Migrating Package Data - 90%
2024-07-26T14:14:14.028075901Z FoundryVTT | 2024-07-26 10:14:14 | [info] Launching World | Migrating Package Data - 93%
2024-07-26T14:14:14.065985268Z FoundryVTT | 2024-07-26 10:14:14 | [info] Launching World | Migrating Package Data - 97%
2024-07-26T14:14:14.083623148Z FoundryVTT | 2024-07-26 10:14:14 | [info] Launching World | Migrating Package Data - 100%
2024-07-26T14:14:14.084430188Z FoundryVTT | 2024-07-26 10:14:14 | [info] Migrating World dnd-high-five to upgraded dnd5e System version 3.3.1
2024-07-26T14:14:14.084617460Z FoundryVTT | 2024-07-26 10:14:14 | [info] Migrating Actor documents to the latest game system data model
2024-07-26T14:14:17.333544227Z FoundryVTT | 2024-07-26 10:14:17 | [info] Successfully migrated 408 Actor documents to the latest system data model.
2024-07-26T14:14:17.333622276Z FoundryVTT | 2024-07-26 10:14:17 | [info] Migrating Cards documents to the latest game system data model
2024-07-26T14:14:17.334390774Z FoundryVTT | 2024-07-26 10:14:17 | [info] Successfully migrated 0 Cards documents to the latest system data model.
2024-07-26T14:14:17.334477310Z FoundryVTT | 2024-07-26 10:14:17 | [info] Migrating ChatMessage documents to the latest game system data model
2024-07-26T14:14:17.643396385Z FoundryVTT | 2024-07-26 10:14:17 | [error] The value provided to a ForeignDocumentField must be a BaseUser instance.
2024-07-26T14:14:17.643460086Z Error: The value provided to a ForeignDocumentField must be a BaseUser instance.
2024-07-26T14:14:17.643471363Z     at ForeignDocumentField._cast (file:///home/foundry/resources/app/common/data/fields.mjs:1994:11)
2024-07-26T14:14:17.643480243Z     at ForeignDocumentField.clean (file:///home/foundry/resources/app/common/data/fields.mjs:202:18)
2024-07-26T14:14:17.643489313Z     at ForeignDocumentField.clean (file:///home/foundry/resources/app/common/data/fields.mjs:1142:18)
2024-07-26T14:14:17.643497786Z     at file:///home/foundry/resources/app/common/data/fields.mjs:1369:40
2024-07-26T14:14:17.643505550Z     at Array.map (<anonymous>)
2024-07-26T14:14:17.643513493Z     at ArrayField._cleanType (file:///home/foundry/resources/app/common/data/fields.mjs:1369:18)
2024-07-26T14:14:17.643521666Z     at ArrayField.clean (file:///home/foundry/resources/app/common/data/fields.mjs:205:17)
2024-07-26T14:14:17.643529586Z     at SchemaField._cleanType (file:///home/foundry/resources/app/common/data/fields.mjs:710:26)
2024-07-26T14:14:17.643537570Z     at SchemaField.clean (file:///home/foundry/resources/app/common/data/fields.mjs:205:17)
2024-07-26T14:14:17.643545370Z     at ChatMessage.cleanData (file:///home/foundry/resources/app/common/abstract/data.mjs:192:24)
2024-07-26T14:14:17.643553463Z     at ChatMessage._initializeSource (file:///home/foundry/resources/app/common/abstract/data.mjs:179:29)
2024-07-26T14:14:17.643561370Z     at new DataModel (file:///home/foundry/resources/app/common/abstract/data.mjs:50:19)
2024-07-26T14:14:17.643569300Z     at new Document (file:///home/foundry/resources/app/common/abstract/document.mjs:27:16)
2024-07-26T14:14:17.643577337Z     at new BaseChatMessage (file:///home/foundry/resources/app/common/documents/chat-message.mjs:24:5)
2024-07-26T14:14:17.643585100Z     at new ServerDocumentMixin (file:///home/foundry/resources/app/dist/database/backend/server-document.mjs:1:877)
2024-07-26T14:14:17.643593007Z     at new ChatMessage (file:///home/foundry/resources/app/dist/database/documents/chat-message.mjs:1:152)
```

I've tried to upgrade to just 3.3.0, but I get the same error. I tried disabling all modules and upgrading again, but get the same error.

**Comment by unsoluble** [comment]
Looks like you’ve got bad data in your chat history that can’t be migrated. Short answer is: Reinstall 3.2.1, launch your world, trash your chat, then try updating again. For all follow-up on this, please head to the Foundry discord, which is where we do all general troubleshooting.

**Comment by Rabulias** [comment]
You can also Export Your Chat Log (the floppy disk icon next to the trash can icon at the bottom of the chat window) once you are back on 3.2.1. Someone _might_ look it over to determine what was bad about it.

**Comment by nikkon226** [comment]
> Looks like you’ve got bad data in your chat history that can’t be migrated. Short answer is: Reinstall 3.2.1, launch your world, trash your chat, then try updating again. For all follow-up on this, please head to the Foundry discord, which is where we do all general troubleshooting.

I trashed the chat and then tried the upgrade again, but I still get the errors. I tried restarting as well, but the same error comes up.
Further up in the logs I get quite a few messages like this:
```
2024-07-29T18:23:31.511539795Z FoundryVTT | 2024-07-29 14:23:31 | [error] An error occurred during the migration of ChatMessage record [rAeg1mzESAEuz5oX] of database "messages":
2024-07-29T18:23:31.511585571Z Error: The value provided to a ForeignDocumentField must be a BaseUser instance.
2024-07-29T18:23:31.511596751Z     at ForeignDocumentField._cast (file:///home/foundry/resources/app/common/data/fields.mjs:1994:11)
2024-07-29T18:23:31.511605531Z     at ForeignDocumentField.clean (file:///home/foundry/resources/app/common/data/fields.mjs:202:18)
2024-07-29T18:23:31.511613855Z     at ForeignDocumentField.clean (file:///home/foundry/resources/app/common/data/fields.mjs:1142:18)
2024-07-29T18:23:31.511622175Z     at file:///home/foundry/resources/app/common/data/fields.mjs:1369:40
2024-07-29T18:23:31.511630108Z     at Array.map (<anonymous>)
2024-07-29T18:23:31.511638178Z     at ArrayField._cleanType (file:///home/foundry/resources/app/common/data/fields.mjs:1369:18)
2024-07-29T18:23:31.511646701Z     at ArrayField.clean (file:///home/foundry/resources/app/common/data/fields.mjs:205:17)
2024-07-29T18:23:31.511654775Z     at SchemaField._cleanType (file:///home/foundry/resources/app/common/data/fields.mjs:710:26)
2024-07-29T18:23:31.511662871Z     at SchemaField.clean (file:///home/foundry/resources/app/common/data/fields.mjs:205:17)
2024-07-29T18:23:31.511670805Z     at ChatMessage.cleanData (file:///home/foundry/resources/app/common/abstract/data.mjs:192:24)
2024-07-29T18:23:31.511678815Z     at ChatMessage._initializeSource (file:///home/foundry/resources/app/common/abstract/data.mjs:179:29)
2024-07-29T18:23:31.511686875Z     at new DataModel (file:///home/foundry/resources/app/common/abstract/data.mjs:50:19)
2024-07-29T18:23:31.511694848Z     at new Document (file:///home/foundry/resources/app/common/abstract/document.mjs:27:16)
2024-07-29T18:23:31.511702805Z     at new BaseChatMessage (file:///home/foundry/resources/app/common/documents/chat-message.mjs:24:5)
2024-07-29T18:23:31.511711221Z     at new ServerDocumentMixin (file:///home/foundry/resources/app/dist/database/backend/server-document.mjs:1:877)
2024-07-29T18:23:31.511742078Z     at new ChatMessage (file:///home/foundry/resources/app/dist/database/documents/chat-message.mjs:1:152)
```

I think that's the same error chain as the other, but it was attached to a specific message. Please note that I have deleted the entire chat log. I did save a copy.

**Comment by unsoluble** [comment]
Please head over to the Foundry discord to follow up on this.
