### ISSUE TITLE
Using the dnd5e.preUseItem hook breaks the attack activity on a weapon

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#4333]
This is a similar issue to #4285, where the existence of the hook is enough to trigger this issue with a simple macro:

```js
Hooks.once("dnd5e.preUseItem", console.log);
```

Steps to reproduce:

1. Drag over one of the SRD weapons onto an actor
2. Run the macro listed above
3. Use the weapon to try and use  that attack activity

Actual Behavior:

Instead of getting the chat card w/ the attack and damage buttons, there's an error in the browser's console:

```
Uncaught (in promise) TypeError: usageConfig.consume?.resources.includes is not a function
    at AttackActivity._createDeprecatedConfigs (mixin.mjs:468:55)
    at AttackActivity.use (mixin.mjs:222:40)
    at Item5e.use (item.mjs:781:23)
```

The line of code is in a function that's only called when some of the old "use item" hooks are used by modules. Again, a similar issue to #4285.

**Comment by kaelad02** [comment]
Just realized I didn't include version numbers... I tested it on 4.0.0 and that's what I grabbed the stack trace from. But this was originally reported by another user on Discord and they were on version 4.0.2.
