### ISSUE TITLE
Adding Bard Colleges throwing an console error

### ISSUE THREAD

**Issue by vinchbr** [foundryvtt/dnd5e#4539]
System DND 5e 4.0.4

Trying to move to the new SRD/PHB 2024 module, when creating a fresh new character to "copy" the old SRD ones, when selecting the Bard College I get this error:

```
foundry.js:655 Error: An error occurred while rendering AdvancementManager 124. Cannot read properties of undefined (reading 'forEach')
[Detected 1 package: system:dnd5e(4.0.4)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at foundry.js:5795:13Caused by: TypeError: Cannot read properties of undefined (reading 'forEach')
[Detected 1 package: system:dnd5e(4.0.4)]
    at actorValues (trait.mjs:62:16)
    at async TraitAdvancement.actorSelected (trait.mjs:178:27)
    at async TraitAdvancement.unfulfilledChoices (trait.mjs:296:23)
    at async TraitFlow.prepareInitialValue (trait-flow.mjs:101:27)
    at async TraitFlow.getData (trait-flow.mjs:38:21)
    at async TraitFlow._render (foundry.js:5838:18)
    at async TraitFlow._render (foundry.js:6572:5)
    at async TraitFlow._render (advancement-flow.mjs:105:5)
    at async AdvancementManager._render (advancement-manager.mjs:473:5)
```

Looks like it is expecting a list to display on the advancement
![Screenshot 2024-10-13 183337](https://github.com/user-attachments/assets/1e4ee960-7f9a-4831-9908-eedb12058c39)

**Comment by unsoluble** [comment]
Please have zero modules enabled while bug testing.

**Comment by vinchbr** [comment]
@unsoluble put the world in safe mode and tried again, same error with SRD 5.1
![Screenshot (1)](https://github.com/user-attachments/assets/f0e48f6e-6ad9-428c-b7ea-41634131bc29)

**Comment by arbron** [comment]
Haven't been able to reproduce this issue.
- Does this only happen with the College of Lore, or other Bard subclasses?
- Does this happen with any other classes?
- Does this happen with the 2014 version of the College of Lore from the SRD or just the PHB version?
- What version of the Player's Handbook module are you running?

**Comment by hakr14** [comment]
Does it happen on a fresh actor?
That is, an actor created and given bard class with no modules.

**Comment by vinchbr** [comment]
> * Does this only happen with the College of Lore, or other Bard subclasses?
All Bard subclasses

> * Does this happen with any other classes?
No

> * Does this happen with the 2014 version of the College of Lore from the SRD or just the PHB version?
2014 works
SRD 5.1 and PHB 2024 do not work
> * What version of the Player's Handbook module are you running?
1.2.0

**Comment by vinchbr** [comment]
Created an empty Actor with no modules and was able to create the character without issues.
