### ISSUE TITLE
Automated level up blocked

### ISSUE THREAD

**Issue by Darkriders98** [foundryvtt/dnd5e#4633]
One of my player got blocked upon automated level up, she can't level up with any classes even after deleting it or something else, and the foundry send this error message:

```Error: Failed data preparation for Actor.GtRzrRIXVQFVZqbk. Expected [%*/], [+\-], end of input, or whitespace but "P" found.
[Detected 1 package: system:dnd5e(4.0.4)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at Actor5e._safePrepareData (foundry.js:10801:15)
    at Actor5e._initialize (foundry.js:10630:19)
    at Actor5e.updateSource (foundry-esm.js:10520:35)
    at #handleUpdateDocuments (foundry-esm.js:56579:13)Caused by: SyntaxError: Expected [%*/], [+\-], end of input, or whitespace but "P" found. (at foundry-esm.js:64400:22)
[Detected 1 package: system:dnd5e(4.0.4)]
    at new peg$SyntaxError (foundry-esm.js:64400:22)
    at peg$buildStructuredError (foundry-esm.js:64775:14)
    at Object.peg$parse [as parse] (foundry-esm.js:65751:13)
    at Roll.parse (foundry-esm.js:63976:45)
    at new Roll (foundry-esm.js:63323:37)
    at AttackActivity.prepareFinalData (attack-data.mjs:189:18)
    at SpellData.prepareFinalActivityData (activities.mjs:292:56)
    at SpellData.prepareFinalData (spell.mjs:235:10)
    at Item5e.prepareFinalAttributes (item.mjs:648:33)
    at actor.mjs:184:37
    at EmbeddedCollection.forEach (foundry-esm.js:5031:9)
    at Actor5e.prepareData (actor.mjs:184:16)
    at Actor5e._safePrepareData (foundry.js:10799:14)
    at Actor5e._initialize (foundry.js:10630:19)
    at Actor5e.updateSource (foundry-esm.js:10520:35)
    at #handleUpdateDocuments (foundry-esm.js:56579:13)```
    
There is also no problem for other players to level up.

# What we tried
- Removing all modules to prevent any conflict between them
- Make my player use the base compendium classe since I copied every classes to make personnal changes
- Tried to level up on other classes

# How to reproduce
I don't know how to reproduce this to be honest, maybe there is something that broke during update from a version to another.

# Other things
- My player use a subclass I created myself, I didn't try to remove this
- She also has self-created spells, that we didn't remove
- I didn't see any weird formula in anything
- I keep the character sheet if you want any further informations

**Comment by Darkriders98** [comment]
Edit:
I just found out how to reproduce because the bug comes with my subclass. I don't really know what I did to break apart since I just copied the oath of devotion already in the compendium. I made some screen of the different tabs:
![image](https://github.com/user-attachments/assets/3133f322-8e35-403f-8780-3e22e9f2adb2)
![image](https://github.com/user-attachments/assets/dbae164c-2afe-4e7b-8963-a41b22e6759b)
![image](https://github.com/user-attachments/assets/914ca31f-9b69-473f-ac94-3c65ebf6a73d)

**Comment by unsoluble** [comment]
Head over to the Foundry discord for all general troubleshooting, please.

**Comment by Darkriders98** [comment]
> Head over to the Foundry discord for all general troubleshooting, please.

Sorry for bothering you, the error messages leads me to think this was on your side. I will head it to foundry issues
